name: Tests

on: [push, pull_request]

jobs:
  tests:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.7"
          - os: ubuntu-latest
            python-version: "3.8"
          - os: ubuntu-latest
            python-version: "3.9"
          - os: ubuntu-latest
            pyton-version: "3.10"
          - os: ubuntu-latest
            pyton-version: "3.11"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Run linter & unit tests
        run: make
